sudo: required

language: go

services:
  - docker

go:
  - 1.11

go_import_path: github.com/saracen/lfscache

env:
  - GO111MODULE=on

script:
- go test ./...

after_success:
- test -n "$TRAVIS_TAG" && docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux

